# Generated by Django 5.0.1 on 2024-04-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retia_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detector',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-04-05T00:00:00+0000'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detector',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
