# Generated by Django 5.0.1 on 2024-04-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retia_api', '0002_alter_activitylog_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='instance',
            field=models.CharField(blank=True, max_length=63),
        ),
    ]
