# Generated by Django 5.0.1 on 2024-03-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retia_api', '0022_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='brand',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
