name: "Build"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup GitHub Action Checkout
        uses: actions/checkout@v4
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.12
          cache: true
      - name: Install the project dependencies
        run: pdm install
      - name: Migrate the database
        run: pdm run migrate
      - name: Run the automated tests
        run: pdm run test
